# Generated by Django 6.1 on 2026-08-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_article_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
